# Generated by Django 4.2.7 on 2023-12-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0002_alter_myuser_is_customer_alter_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
