# Generated by Django 5.0 on 2023-12-22 05:39

import coffe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0002_alter_myuser_managers_alter_myuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=coffe.models.get_default_image, null=True, upload_to='images/user_uploads', verbose_name='CategoryImage'),
        ),
    ]
