# Generated by Django 5.0 on 2023-12-17 07:45

import coffe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0003_alter_myuser_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default=coffe.models.get_default_image, null=True, upload_to='images/user_uploads', verbose_name='ItemImage'),
        ),
    ]
